### ISSUE TITLE
Error al crear la BD

### ISSUE THREAD

**Issue by jorgeramirez** [jorgeramirez/LPM#1]
Cuando ejecuto el comando paster setup-app development.ini
lanza el siguiente error
FATAL:  no existe el rol <<administrador>>

P.D.: estoy probando este tema de los issues =D

**Comment by jorgeramirez** [comment]
Ese error me daba porque no tenia el rol administrador en mi BD
como supone la linea sqlalchemy.url en development.ini

En fin me sigue dando error en este caso, dice entre otras cosas

sqlalchemy.exc.CircularDependencyError: Circular dependency detected

**Comment by nahu** [comment]
lo que pasa es que mi usario en postgrest es administrador, cambiar noms en
tu development.ini a admin o crea un usuario administrador, jaja...

El 22 de abril de 2011 12:24, jorgeramirez <
reply@reply.github.com>escribi:

> Cuando ejecuto el comando paster setup-app development.ini
> lanza el siguiente error
> FATAL:  no existe el rol <<administrador>>
> 
> P.D.: estoy probando este tema de los issues =D
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/jorgeramirez/LPM/issues/1

## 

Nahuel Hernndez

**Comment by jorgeramirez** [comment]
en efecto eso ya solucione XD

El 22 de abril de 2011 16:54, nahu <
reply@reply.github.com>escribi:

> lo que pasa es que mi usario en postgrest es administrador, cambiar noms en
> tu development.ini a admin o crea un usuario administrador, jaja...
> 
> El 22 de abril de 2011 12:24, jorgeramirez <
> reply@reply.github.com>escribi:
> 
> > Cuando ejecuto el comando paster setup-app development.ini
> > lanza el siguiente error
> > FATAL:  no existe el rol <<administrador>>
> > 
> > P.D.: estoy probando este tema de los issues =D
> > 
> > ## 
> > 
> > Reply to this email directly or view it on GitHub:
> > https://github.com/jorgeramirez/LPM/issues/1
> 
> ## 
> 
> Nahuel Hernndez
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/jorgeramirez/LPM/issues/1#comment_1045566

## 

Jorge Daniel Ramrez Medina.
_Ingeniera Informtica *_FP-UNA.**

---
- _jorgedaniel@ramirezmedina.com jorgeramirez1990@gmail.com_
- _jorgeramirez1990@gmail.com_
- _jorge.ramirez1990@hotmail.com_

**Comment by nahu** [comment]
pero hay millones errores
ahora estoy intentando solucionar....

El 22 de abril de 2011 17:05, jorgeramirez <
reply@reply.github.com>escribi:

> en efecto eso ya solucion XD
> 
> El 22 de abril de 2011 16:54, nahu <
> reply@reply.github.com>escribi:
> 
> > lo que pasa es que mi usario en postgrest es administrador, cambiar noms
> > en
> > tu development.ini a admin o crea un usuario administrador, jaja...
> > 
> > El 22 de abril de 2011 12:24, jorgeramirez <
> > reply@reply.github.com>escribi:
> > 
> > > Cuando ejecuto el comando paster setup-app development.ini
> > > lanza el siguiente error
> > > FATAL:  no existe el rol <<administrador>>
> > > 
> > > P.D.: estoy probando este tema de los issues =D
> > > 
> > > ## 
> > > 
> > > Reply to this email directly or view it on GitHub:
> > > https://github.com/jorgeramirez/LPM/issues/1
> > 
> > ## 
> > 
> > Nahuel Hernndez
> > 
> > ## 
> > 
> > Reply to this email directly or view it on GitHub:
> > https://github.com/jorgeramirez/LPM/issues/1#comment_1045566
> 
> ## 
> 
> Jorge Daniel Ramrez Medina.
> _Ingeniera Informtica *_FP-UNA.**
> 
> ---
> - _jorgedaniel@ramirezmedina.com jorgeramirez1990@gmail.com_
> - _jorgeramirez1990@gmail.com_
> - _jorge.ramirez1990@hotmail.com_
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/jorgeramirez/LPM/issues/1#comment_1045623

## 

Nahuel Hernndez

**Comment by jorgeramirez** [comment]
osea solucionó lo del rol administrador, pero siguen millones de errores =D

**Comment by nahu** [comment]
hay relaciones en la que me pide que haga joins increbles, jaja...

2011/4/22 jorgeramirez <
reply@reply.github.com>

> osea solucion lo del rol administrador, pero siguen millones de errores =D
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/jorgeramirez/LPM/issues/1#comment_1045679

## 

Nahuel Hernndez

**Comment by jorgeramirez** [comment]
JOJO. tiene algo que ver con primaryjoin y secondaryjoin?

**Comment by nahu** [comment]
s

2011/4/22 jorgeramirez <
reply@reply.github.com>

> JOJO. tiene algo que ver con primaryjoin y secondaryjoin?
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/jorgeramirez/LPM/issues/1#comment_1045709

## 

Nahuel Hernndez

**Comment by nahu** [comment]
conectate pues al gtalk

El 22 de abril de 2011 17:30, Nahuel Hernndez nahuel.11990@gmail.comescribi:

> s
> 
> 2011/4/22 jorgeramirez <
> reply@reply.github.com>
> 
> > JOJO. tiene algo que ver con primaryjoin y secondaryjoin?
> > 
> > ## 
> > 
> > Reply to this email directly or view it on GitHub:
> > https://github.com/jorgeramirez/LPM/issues/1#comment_1045709
> 
> ## 
> 
> Nahuel Hernndez

## 

Nahuel Hernndez
