### ISSUE TITLE
Actualizar datos de proyecto

### ISSUE THREAD

**Issue by jorgeramirez** [jorgeramirez/LPM#2]
Cuando uno modifica los datos de un proyecto (nombre o descripción) 
después guarda esos cambios, las fases de ese proyecto pierden
el identificador a dicho proyecto, es decir el proyecto deja de tener
fases.

**Comment by nahu** [comment]
qu es esto?

El 20 de mayo de 2011 14:27, jorgeramirez <
reply@reply.github.com>escribi:

> Cuando uno modifica los datos de un proyecto (nombre o descripcin)
> despus guarda esos cambios, las fases de ese proyecto pierden
> el identificador a dicho proyecto, es decir el proyecto deja de tener
> fases.
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/jorgeramirez/LPM/issues/2

## 

Nahuel Hernndez

**Comment by jorgeramirez** [comment]
la sección de issues de github, por cierto vanessa me aclaro ya el porqué.
